name: Deploy To gh-pages
on:
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - 'UI/**'

defaults:
  run:
    working-directory: UI/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm ci
      working-directory: UI/
    - run: npm run build:subdir
      working-directory: UI/
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        # for angular17 and above, build output is dist/<name>/browser
        FOLDER: UI/dist/jutsu-generator-client/browser
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
